---
- name: Pack Data
  command: "{{ item }}"
  with_items:
  - apt install -rsync
  - mkdir /migrate
  - docker container exec "{{ container1 }}" /usr/bin/mysqldump -u root --password="{{ DBpassword }}" --all-databases > /migrate/backup.sql
  - tar -cvf /migrate/web.tar /opt/web
  - tar -cvf /migrate/home.tar /home
- name: Tranferdata
  command: "{{ item }}"
  with_items:
  - rsync -avz --no-o --no-g /migrate/* "{{ DestIP }}"::migrate
- script: script.sh
  