- name: Pull data from migrate directory
  ansible.posix.synchronize:
    mode: pull
    src: rsync://{{ SourceIP }}/migrate
    dest: /opt/rsync/
    rsync_opts:
      - "-av"
  register: rsync1

- name: Pull data debugging
  debug: 
    msg: "{{ rsync1 }}"
    verbosity: 2
  when: rsync1 is defined

- name: Push data to DestOS
  ansible.posix.synchronize:
    src: /opt/rsync/
    dest: rsync://{{ item }}/migrate
    mode: push
  loop: "{{ DestIP }}"
  register: rsync2

- name: Push data debugging
  debug: 
    msg: "{{ rsync2 }}"
    verbosity: 2
  when: rsync2 is defined