---
- name: Dump container's database and Linux user
  shell: "{{ item }}"
  with_items:
    - docker container exec {{ dbcontainername }} /usr/bin/mysqldump -u root --password="{{ DBpassword }}" --all-databases > /migrate/backup.sql
    - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534)' /etc/passwd > /migrate/passwd.sync"
    - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534)' /etc/group > /migrate/group.sync"
    - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534) {print $1}' /etc/passwd | tee - | egrep -f - /etc/shadow > /migrate/shadow.sync"
    - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534) {print $1}' /etc/group | tee - | egrep -f - /etc/gshadow > /migrate/gshadow.sync"
  register: dump

- name: Shell output
  debug:
    msg: "{{ dump.stdout }}"
    verbosity: 2
  when: dump.stdout is defined

- name: Compress web data and home directory
  community.general.archive:
    path:
    - /opt/web
    - /home
    format: tar
    dest: /migrate/data.tar
  register: compress

- name: Compress state
  debug:
    msg: "{{ compress.state }}"
    verbosity: 2