---
- name: Docker import
  shell: "{{ item }}"
  with_items:
  - "cat /opt/rsync/passwd.sync >> /etc/passwd"
  - "cat /opt/rsync/group.sync >> /etc/group"
  - "cat /opt/rsync/shadow.sync >> /etc/shadow"
  - "cat /opt/rsync/gshadow.sync >> /etc/gshadow"
  - tar -xvf /opt/rsync/home.tar -C /
  - docker container run -d --name db -e MYSQL_ROOT_PASSWORD="{{ dbpassword }}" -v /opt/mysql mysql
  - "cat /opt/rsync/backup.sql | docker container exec -i db mysql -u root --password="{{ dbpassword }}""