---
- name: Update and install Docker, rsync, wget
  shell: "{{ item }}"
  with_items:
  - mkdir /opt/rsync
  - apt-get update
  - apt-get install -y rsync wget
  - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce=18.06.3~ce~3-0~debian containerd.io
  - wget -P /etc https://gitlab.fpt.vn/intern/iac-tranfer-server/-/raw/master/rsyncd.conf
  - systemctl restart rsync
 #ignore_errors: yes