- name: Install sudo if doesn't exist
  apt:
    pkg:
      - sudo
    update_cache: yes

- name: Add the user 'ansible' with uid 1050 and a primary group of 'sudo'
  user:
    name: ansible
    uid: "{{ ansible_uid }}"

- name: Give sudo privilege to ansible
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible'
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Create SSH key folder
  file:
    path: /home/ansible/.ssh
    state: directory

- name: Send SSH key from ansible host
  copy:
    src: files/id_rsa.pub
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible