- name: Install rsync
  apt:
    pkg:
    - rsync
    update_cache: yes
  register: apt

- name: Apt install output
  debug:
    msg: "{{ apt.stdout.split('\n') }}"
    verbosity: 2
  when: apt.stdout is defined

- name: Apt install error
  debug:
    msg: "{{ apt.stderr.split('\n') }}"
    verbosity: 2
  when: apt.stderr is defined

- name: Send rsync config
  copy:
    src: "{{ rsyncdconf }}"
    dest: /etc/rsyncd.conf
    backup: yes
  notify:
  - Restart service rsync